image: ubuntu:xenial


# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

before_script:
  - apt-get update && apt-get install curl -y
  - curl -sL https://deb.nodesource.com/setup_8.x |  bash -
  - apt-get install ruby devscripts debhelper nodejs git -y
  - gem install sass
  - npm install --upgrade --global grunt-cli npm bower yarn

stages:
  - build
  
build:
  stage: build
  script:
    - yarn
    - bower install --allow-root
    - grunt clean package docker
  

