sudo: required
language: node_js
node_js: node

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.15.0 

before_install:
  - docker version

script:
  - docker-compose -p web up -d --build && sleep 20
  - docker exec web_kapture_1 curl localhost:9000
  - docker-compose -p web logs
  
  - docker run -it --privileged --rm --network=web_default -e BASE_URL=http://web_kapture_1:9000 -v /dev/shm:/dev/shm -v $(pwd):/protractor webnicer/protractor-headless
