sudo: required
language: node_js
node_js: node

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.15.0 

before_install:
  - docker version

script:
  - docker-compose up -d --build
  
  - echo docker run \
    -e BASE_URL=http://web_web_1:9000 \
    -w /build \
    --network web_default \
    $(docker images --filter "label=builder=true" -q | head -n1) \
    npm run test
