sudo: required
language: node_js
node_js: node

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.15.0 
    - BASE_URL=http://localhost:9000

before_install:
  - apt-get update 
  - apt-get install ruby-dev -y
  - npm install -g yarn grunt-cli
  - gem install compass

install:
  - yarn

script:
  - docker-compose up -d --build
  - node_modules/protractor/bin/protractor
