sudo: required
language: node_js
node_js: node

services:
  - docker
addons:
  packages:
    - docker-ce

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.15.0 
    - BASE_URL=http://localhost:9000

before_install:
  - sudo apt-get update 
  - sudo apt-get install ruby-dev -y
  - npm install -g yarn grunt-cli
  - gem install compass
  - Xvfb :0 -ac -screen 0 1024x768x24 &

install:
  - yarn
  - node_modules/.bin/webdriver-manager update

script:
  - docker-compose up -d --build
  - node_modules/protractor/bin/protractor
