version: '3.1'

services:

  kapture:
    build: .
    image: kapture:devel
    volumes:
      - config:/config
    environment:
      TRANSMISSION_USER: admin
      TRANSMISSION_PASS: password      
      FLEXGET_USERNAME: flexget
      FLEXGET_PASSWORD: my super password
      # FLEXGET_API_TOKEN: 
    ports:
      - '9000:9000'


  # kapture-iot:
  #   build: ../kapture-iot
  #   image: kapture-iot:latest
    

  
  transmission:
    image: dperson/transmission
    # network_mode: host
    ports:
      - '51413:51413'
      - '51413:51413/udp'
      - '9091:9091'
    environment:
      TRUSER: admin
      TRPASSWD: password
    volumes:
      - data:/var/lib/transmission-daemon/downloads



  flexget:
    image: gaieges/flexget
    environment:
      FLEXGET_PASSWORD: my super password
    


  plex:
    image: plexinc/pms-docker
    # network_mode: host
    ports: 
      - '32400:32400'
    volumes:
      - data:/data
    
volumes:
  config:
  data:
