version: '2.3'

services:

  kapture:
    build: 
      context: .
      target: build
    image: kapturebox/web
    volumes:
      - ./config:/config
      - ./media:/media
      - /build/node_modules
      - .:/build
    command: grunt serve
    environment:
      TRANSMISSION_USER: admin
      TRANSMISSION_PASS: password
      FLEXGET_USERNAME: flexget
      FLEXGET_PASSWORD: mySuperPassword
      # NODE_DEBUG: request
      # FLEXGET_API_TOKEN:
    ports:
      - '9000:9000'

  transmission:
    image: dperson/transmission
    ports:
      - '51413:51413'
      - '51413:51413/udp'
      - '9091:9091'
    environment:
      TRUSER: admin
      TRPASSWD: password
    volumes:
      - ./media:/var/lib/transmission-daemon/downloads

  flexget:
    image: gaieges/flexget
    environment:
      FLEXGET_PASSWORD: mySuperPassword
    ports:
      - "5050:5050"

  plex:
    image: plexinc/pms-docker
    ports: 
      - '32400:32400'
    volumes:
      - ./media:/data
