---
# tasks file for ansible/roles/initial-setup
- name: ensure system is up to date
  apt: upgrade=dist
  register: system_upgraded

- name: expand root partition
  command: raspi-config --expand-rootfs
  when: ansible_lsb.id == "Raspbian"

- name: disable lightdm on boot
  template:
    src: lightdm.override.j2
    dest: /etc/init/lightdm.override
    mode: 0644
    owner: root
    group: root

- name: setup initial needed packages
  apt: pkg="{{ item }}" state=present force=yes
  with_items:
    - python2.7-dev
    - python-setuptools
    - nodejs
    - apt-transport-https
    - usbmount


- name: ensure kapture group is setup correctly
  group: name=kapture system=yes state=present

- name: ensure kapture users are setup correctly
  user:
    groups: sudo,kapture
    name: "{{ kapture_user }}"
    createhome: yes
    home: /var/lib/kapture
    state: present


- name: change storage path if running via vagrant
  set_fact: storage_block_device=/dev/sdb
  when: ansible_lsb.id != "Raspbian"

# not the best way to check for this stuff, especially with multiple drives.
# works in the meantime though
# eventually i'd like to use lvm and you add a disk and it'll automatically be added to the lvm layer
- name: get usb disk mount status
  shell: "mountpoint -q {{ storage_path }}0"
  ignore_errors: true
  register: storage_mount_stat

- name: setup disk if needed
  include: setup-disk.yml
  when: storage_mount_stat.rc != 0


- name: restart machine
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true
  when: system_upgraded.changed and ansible_lsb.id == "Raspbian"

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started timeout=600
  become: false
  when: system_upgraded.changed and ansible_lsb.id == "Raspbian"
