---
# tasks file for ansible/roles/initial-setup
- name: ensure system is up to date
  apt: upgrade=dist
  register: system_upgraded

- name: restart machine
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true
  when: system_upgraded.changed

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started timeout=600
  become: false
  when: system_upgraded.changed
